eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  profiles:
    active: default