version: "3.8"

services:
  petshop-db:
    image: postgres
    volumes:
      - petshop-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: rar432

  petshop-redis:
    image: redis
    volumes:
      - petshop-redis:/data

  petshop-discovery:
    image: petshop-discovery-srvc
    environment:
      PORT: 8761

  petshop-config-server:
    depends_on:
      - petshop-discovery
    image: petshop-config-srvc
    environment:
      PORT: 8888
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-admin-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-admin-srvc
    ports:
      - "8091:8090"
    environment:
      PORT: 8090
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-attendant-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-attendant-srvc
    environment:
      PORT: 8091
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-customer-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-customer-srvc
    environment:
      PORT: 8092
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-veterinarian-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-veterinarian-srvc
    environment:
      PORT: 8093
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-visit-service:
    depends_on:
      - petshop-db
      - petshop-redis
      - petshop-config-server
      - petshop-discovery
      - petshop-customer-service
      - petshop-veterinarian-service
    image: petshop-visit-srvc
    environment:
      PORT: 8094
      DB_URL: petshop-db
      REDIS_HOST: petshop-redis
      REDIS_PORT: 6379
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-auth-service:
    depends_on:
      - petshop-config-server
      - petshop-discovery
      - petshop-admin-service
      - petshop-attendant-service
      - petshop-customer-service
      - petshop-veterinarian-service
    image: petshop-auth-srvc
    environment:
      PORT: 8094
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-gateway:
    depends_on:
      - petshop-config-server
      - petshop-discovery
      - petshop-admin-service
      - petshop-attendant-service
      - petshop-customer-service
      - petshop-veterinarian-service
      - petshop-auth-service
    image: petshop-gateway
    ports:
      - "7778:7777"
    environment:
      PORT: 7777
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

volumes:
  petshop-db:
  petshop-redis:
