version: "3.8"

services:
  petshop-db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - petshop-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: rar432

  petshop-redis:
    image: redis
    volumes:
      - petshop-redis:/data
    ports:
      - "6380:6379"

  petshop-discovery:
    image: petshop-discovery-srvc
    ports:
      - "8762:8761"
    environment:
      PORT: 8761

  petshop-config-server:
    depends_on:
      - petshop-discovery
    image: petshop-config-srvc
    ports:
      - "8889:8888"
    environment:
      PORT: 8888
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-admin-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-admin-srvc
    ports:
      - "8091:8090"
    environment:
      PORT: 8090
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-attendant-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-attendant-srvc
    ports:
      - "8092:8091"
    environment:
      PORT: 8091
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-customer-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-customer-srvc
    ports:
      - "8093:8092"
    environment:
      PORT: 8092
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-veterinarian-service:
    depends_on:
      - petshop-db
      - petshop-config-server
      - petshop-discovery
    image: petshop-veterinarian-srvc
    ports:
      - "8094:8093"
    environment:
      PORT: 8093
      DB_URL: petshop-db
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

  petshop-visit-service:
    depends_on:
      - petshop-db
      - petshop-redis
      - petshop-config-server
      - petshop-discovery
      - petshop-customer-service
      - petshop-veterinarian-service
    image: petshop-visit-srvc
    ports:
      - "8095:8094"
    environment:
      PORT: 8094
      DB_URL: petshop-db
      REDIS_HOST: petshop-redis
      REDIS_PORT: 6379
      DISCOVERY_SERVICE_URL: http://petshop-discovery:8761/eureka

volumes:
  petshop-db:
  petshop-redis:
