eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

server:
  port: ${PORT:7777}

spring:
  cloud:
    gateway:
      routes:
        - id: admin-email
          uri: no://op
          predicates:
            - Path=/api/admin/email
          filters:
            - SetStatus=403

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

        - id: customer-email
          uri: no://op
          predicates:
            - Path=/api/customer/email
          filters:
            - SetStatus=403

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customer/**

        - id: vet-email
          uri: no://op
          predicates:
            - Path=/api/veterinarian/email
          filters:
            - SetStatus=403

        - id: veterinarian-service
          uri: lb://veterinarian-service
          predicates:
            - Path=/api/veterinarian/**

        - id: visit-service
          uri: lb://visit-service
          predicates:
            - Path=/api/visit/**

        - id: attendant-email
          uri: no://op
          predicates:
            - Path=/api/attendant/email
          filters:
            - SetStatus=403

        - id: attendant-service
          uri: lb://attendant-service
          predicates:
            - Path=/api/attendant/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**