eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8092
  servlet:
    context-path: /api

spring:
  application:
    name: admin-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: default