eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

server:
  port: ${PORT:8082}

spring:
  application:
    name: admin-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  config:
    import: optional:configserver:config-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localholst}:${DB_PORT:5432}/petshop-admin
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rar432}
  profiles:
    active: ${PROFILE:default}