eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

server:
  port: ${PORT:8091}

spring:
  application:
    name: attendant-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
  config:
    import: optional:configserver:config-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/petshop-attendant}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rar432}
  profiles:
    active: ${PROFILE:default}