eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: visits-service
  config:
    import: configserver:http://localhost:8888
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  profiles:
    active: default
  cache:
    type: redis
  redis:
    host: localhost
    port: 6666

management.health.circuitbreakers.enabled: true

resilience4j:
  circuitbreaker:
    instances:
      customerGetById:
        failureRateThreshold: 60
        slidingWindowSize: 5
      customersGetByIdIn:
        failureRateThreshold: 60
        slidingWindowSize: 5
      vetGetById:
        failureRateThreshold: 60
        slidingWindowSize: 5
      vetsGetByIdIn:
        failureRateThreshold: 60
        slidingWindowSize: 5
  bulkhead:
    instances:
      customerGetById:
        maxWaitDuration: 500ms
        maxConcurrentCalls: 10
      customersGetByIdIn:
        maxWaitDuration: 500ms
        maxConcurrentCalls: 10
      vetGetById:
        maxWaitDuration: 500ms
        maxConcurrentCalls: 10
      vetsGetByIdIn:
        maxWaitDuration: 500ms
        maxConcurrentCalls: 10
